In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
from data import ablate_interactions, generate_data
from utils import get_default_model, compile_model

In [4]:
dataset = np.load('data/simulated_all.npz')
x_train, y_train = dataset['x_train'], dataset['y_train']
x_test,  y_test  = dataset['x_test'],  dataset['y_test']

In [5]:
spec_df = pd.read_csv('data/simulated_all_spec.csv')

In [6]:
model = get_default_model(x_train.shape[1])
compile_model(model)

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                704       
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 65        
Total params: 9,089
Trainable params: 9,089
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.fit(x=x_train,
          y=y_train,
          batch_size=128,
          epochs=200,
          verbose=2,
          validation_data=(x_test, y_test))

Train on 3200 samples, validate on 800 samples
Epoch 1/200
3200/3200 - 0s - loss: 0.7232 - mean_squared_error: 0.7232 - val_loss: 0.2041 - val_mean_squared_error: 0.2041
Epoch 2/200
3200/3200 - 0s - loss: 0.1329 - mean_squared_error: 0.1329 - val_loss: 0.0845 - val_mean_squared_error: 0.0845
Epoch 3/200
3200/3200 - 0s - loss: 0.0605 - mean_squared_error: 0.0605 - val_loss: 0.0546 - val_mean_squared_error: 0.0546
Epoch 4/200
3200/3200 - 0s - loss: 0.0469 - mean_squared_error: 0.0469 - val_loss: 0.0566 - val_mean_squared_error: 0.0566
Epoch 5/200
3200/3200 - 0s - loss: 0.0400 - mean_squared_error: 0.0400 - val_loss: 0.0424 - val_mean_squared_error: 0.0424
Epoch 6/200
3200/3200 - 0s - loss: 0.0328 - mean_squared_error: 0.0328 - val_loss: 0.0372 - val_mean_squared_error: 0.0372
Epoch 7/200
3200/3200 - 0s - loss: 0.0264 - mean_squared_error: 0.0264 - val_loss: 0.0356 - val_mean_squared_error: 0.0356
Epoch 8/200
3200/3200 - 0s - loss: 0.0234 - mean_squared_error: 0.0234 - val_loss: 0.0340 - 

In [8]:
y_train

array([0.82355572, 1.96891546, 0.20987126, ..., 0.81907398, 1.28670346,
       0.45811492])

In [19]:
interactions = np.zeros((x_train.shape[0], x_train.shape[1], x_train.shape[1]))
interactions[0, 0, 2] = 1.0

In [20]:
interactions.shape

(3200, 10, 10)

In [26]:
ablate_interactions(x=x_train,
                    interactions=interactions,
                    spec_df=spec_df,
                    k=1)

array([1.07056519, 1.9689155 , 0.20987121, ..., 0.819074  , 1.28670349,
       0.45811492])

In [13]:
y_train

array([0.82355572, 1.96891546, 0.20987126, ..., 0.81907398, 1.28670346,
       0.45811492])

In [18]:
spec_df

first_feature  second_feature interaction_type  coefficient
0               1               9          minimum    -0.136034
1               3               4          minimum    -0.313025
2               1               6        squaresum    -0.129042
3               4               8          minimum    -0.173710
4               3               8          minimum    -0.023051
5               0               6          maximum     0.052945
6               4               9        squaresum     0.074540
7               1               5         multiply     0.181430
8               2               6        squaresum    -0.176251
9               0               8          maximum    -0.098451
10              0               2          maximum     0.380028
11              0               5          minimum    -0.193580
12              4               7         multiply    -0.014922
13              0               1          minimum    -0.162640
14              2               4          minimum    -0.256937
15              1               4          minimum    -0.213281
16              7               9        squaresum    -0.015907
17              3               5         multiply    -0.223076
18              1               8         multiply    -0.007132
19              0               3          minimum     0.166325