In [42]:
%load_ext autoreload
%autoreload 2

In [44]:
import tensorflow as tf
import numpy as np
from path_explain.path_explainer_tf import PathExplainerTF

In [25]:
x = tf.constant([[2.0, 5.0], [6.0, 8.0]])

In [31]:
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.square(x)
    z = tf.reduce_sum(y, axis=-1)
t.gradient(z, x)

<tf.Tensor: id=147, shape=(2, 2), dtype=float32, numpy=
array([[ 4., 10.],
       [12., 16.]], dtype=float32)>

In [34]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(1, input_shape=(2,)))

In [37]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[0.3474363],
        [0.6916834]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [79]:
k = tf.constant([[200.0, 500.0], [6.0, 8.0]])

In [80]:
with tf.GradientTape() as t:
    t.watch(k)
    y = model(k)
t.gradient(y, k)

<tf.Tensor: id=541, shape=(2, 2), dtype=float32, numpy=
array([[0.3474363, 0.6916834],
       [0.3474363, 0.6916834]], dtype=float32)>

In [83]:
num_samples = 10
explainer = PathExplainerTF(model)
eg_single = explainer._single_attribution(x[0], np.zeros((1, 2)).astype(np.float32),
                            current_alphas=np.linspace(0.0, 1.0, num_samples).astype(np.float32),
                            num_samples=num_samples, batch_size=50,
                            use_expectation=False, output_index=0)

tf.Tensor(
[[0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]
 [0.3474363 0.6916834]], shape=(10, 2), dtype=float32)
tf.Tensor(
[[2. 5.]
 [2. 5.]
 [2. 5.]
 [2. 5.]
 [2. 5.]
 [2. 5.]
 [2. 5.]
 [2. 5.]
 [2. 5.]
 [2. 5.]], shape=(10, 2), dtype=float32)


In [84]:
eg_single

array([0.6948727, 3.4584165], dtype=float32)

In [74]:
model.weights[0][:, 0] * x[0]

<tf.Tensor: id=443, shape=(2,), dtype=float32, numpy=array([0.6948726, 3.458417 ], dtype=float32)>

In [67]:
model(x[0:1])

<tf.Tensor: id=414, shape=(1, 1), dtype=float32, numpy=array([[4.15329]], dtype=float32)>

In [61]:
eg_single

array([0.34743634, 1.7292084 ], dtype=float32)